### ISSUE TITLE
Manage multiple Makefiles

### ISSUE THREAD

**Issue by Lecrapouille** [lfmunoz/vscode-makefile-term#7]
Hi ! Interesting project, but unusable in my case because your tool seems not managing several Makefiles.
All my projects follow this tree:
```
MyProject/
     + Makefile
     + src/
          + *.cpp
     + examples/
          + *.cpp
          + Makefile
     + tests/
          + *.cpp
          + Makefile
```

- MyProject/Makefile compiles src/*.cpp into but depending on the project either static lib or a binary application.
- MyProject/examples/Makefile compiles examples using the static lib
- MyProject/test/Makefile unit tests.

Ideas. Instead of :

```
{
    "makefile.launchConfigurations": [
        {
            "cwd": []
            "binaryPath": []
            "binaryArgs": []
        }
    ]
}
```

is to have a graph of dependencies (sorry, I'm a dumb in JSON syntax):
```
{
    "makefile.launchConfigurations": [
        {
            "name": "MyProject/Makefile"
            "cwd": []
            "binaryPath": []
            "binaryArgs": []
            "afterSuccess": [ "MyProject/examples/Makefile", "MyProject/tests/Makefile" ]
            "dependOn": []
        },
        {
            "name": "MyProject/examples/Makefile"
            "cwd": []
            "binaryPath": []
            "binaryArgs": []
            "afterSuccess": []
            "dependOn": [ "MyProject/Makefile" ]
        },
        {
            "name": "MyProject/tests/Makefile"
            "cwd": []
            "binaryPath": []
            "binaryArgs": []
            "afterSuccess": []
            "dependOn": [ MyProject/Makefile" ]
        },
    ]
}
```

- When MyProject/Makefile ends with success, it will call MyProject/examples/Makefile then MyProject/tests/Makefile.
- I don't know if better to define the graph with "afterSuccess" or "calledBy" or "dependOn" rules.
- Depending on where you are in the folder (active document), find the first Makefile rule, execute it.
- Probably beware of graph cycles:
   - If I'm placed on MyProject and I call MyProject/Makefile it will call MyProject/tests/Makefile but event if this one depends on MyProject/Makefile it will not call it (upper folder hierarchy).
   - If I'm placed on MyProject/tests and I call Makefile this one depends on MyProject/Makefile it will call it first (lower folder hierarchy)

**Comment by lfmunoz** [comment]
Not sure I understand your problem. You are trying to call multiple Makefiles in a chain and you want a tool to do that for you?  

It is way better to call Makefiles within other Makfiles and chain them. Make is already designed to do that. This extension is a convenient way to call Makefiles it shouldn't be doing anything you can't do from he console.  Get your project working from command line first, then use tool to conveniently execute targets by clicking.  

See: 
https://www.gnu.org/software/make/manual/make.html#Recursion
http://aggregate.org/rfisher/Tutorials/Make/make6.html

**Comment by Lecrapouille** [comment]
`You are trying to call multiple Makefiles in a chain` 
yes

`and you want a tool to do that for you?`
Not particularly because I have my own scripts. Just testing your tools. I used instead `tasks.json` and it does the job.
