### ISSUE TITLE
System cannot find the path specified

### ISSUE THREAD

**Issue by gagmeng** [lfmunoz/vscode-makefile-term#8]
When executing the bulid with  command"cd "f:\test\prj"; make -f prj.mk target_test", the following error message "System cannot find the path specified" is obtained.  Modify the command to "cd "f:\test\prj" && make -f prj.mk target_test" , then it can be build normally.

**Comment by lfmunoz** [comment]
updated to use `&&` instead of  `;`  in version 0.1.1
